# This is a basic workflow to help you get started with Actions

name: artifact

on:
  push:
    branches:
    - main

  schedule:
    - cron: '0 0 * 9 2-6' #At 00:00 on every day-of-week from Tuesday through Saturday in September.

env:
  FILE_NAME: hello-server

jobs:
  build-go:
    name: Build Go 
    runs-on: ubuntu-latest
    steps:

    - name: Checkout Go Code
      uses: actions/checkout@v4

    - name: Build ${{ env.FILE_NAME }} for ubuntu-latest
      run: go build ${{ env.FILE_NAME }}.go

    - name: Build ${{ env.FILE_NAME }} for windows-latest
      run: GOOS=windows GOARCH=amd64 go build ${{ env.FILE_NAME }}.go

  test-step:
    name: Test Go Build
    runs-on: ubuntu-latest
    needs: 
     - build-go
    steps:
    
    - name: Checkout Go Code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'  # Substitua pela versão do Go que você está usando

    - name: Initialize Go Modules
      run: go mod tidy

    - name: Run Go Tests
      uses: n8maninger/action-golang-test@v1

  upload-artifacts:
    name: Upload Artifacts
    runs-on: ubuntu-latest
    needs: 
      - build-go
      - test-step
    steps:
      - name: Upload artifact for linux
        uses: actions/upload-artifact@v4
        with:
          name: linux
          path: ./${{ env.FILE_NAME }}
        
      - name: Upload artifact for windows
        uses: actions/upload-artifact@v4
        with:
          name: windows
          path: ./${{ env.FILE_NAME }}.exe
    
      

    
