# This is a basic workflow to help you get started with Actions

name: artifact

on:
  push:
    branches:
    - main

  schedule:
    - cron: '0 0 * 9 2-6' #At 00:00 on every day-of-week from Tuesday through Saturday in September.

env:
  FILE_NAME: hello-server

jobs:
  build-go:
    name: Build Go
    runs-on: ubuntu-latest
    steps:

    - name: Checkout Go Code
      uses: actions/checkout@v4

    - name: Build ${{ env.FILE_NAME }} for ubuntu-latest
      run: go build ${{ env.FILE_NAME }}.go

    - name: Build ${{ env.FILE_NAME }} for windows-latest
      run: GOOS=windows GOARCH=amd64 go build ${{ env.FILE_NAME }}.go

    - name: Upload artifact for linux
      uses: actions/upload-artifact@v4
      with:
        name: linux
        path: ./${{ env.FILE_NAME }}

    - name: Upload artifact for windows
      uses: actions/upload-artifact@v4
      with:
        name: windows
        path: ./${{ env.FILE_NAME }}.exe

  build:
    # Name the Job
    name: Lint Code Base
    # Set the agent to run on
    runs-on: ubuntu-latest
     
    permissions:
      contents: read
      packages: read
      statuses: write

    ##################
    # Load all steps #
    ##################
    steps:
      ##########################
      # Checkout the code base #
      ##########################
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          # Full git history is needed to get a proper
          # list of changed files within `super-linter`
          fetch-depth: 0  
 
